
spring.application.name=ayvy
server.port=8012


spring.datasource.url=jdbc:sqlserver://localhost:1433;databseName=apidb;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=@ITB123456

spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enable=true
spring.h2.console.path=/h2-console